
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "gce"
  config.vm.provision "shell" do |s|
    s.path = "~/dev/ProvisionScript/debian/debian-7.6-baseSetup.sh"
  end
  config.vm.provision "shell" do |s|
    s.path = "~/dev/ProvisionScript/debian/debian-7.6-oracleJdk.sh"
    s.args = "sky 8" 
  end
  config.vm.provision "shell" do |s|
    s.path = "~/dev/ProvisionScript/debian/debian-7.6-postgreSql.sh"
    s.args = "sky 9.3 wheezy" 
  end
  config.vm.provision "shell" do |s|
    s.path = "~/dev/ProvisionScript/debian/debian-7.6-sonarqube.sh"
    s.args = "sky 3.7.4 9.3" 
  end
  config.vm.provision "shell" do |s|
    s.path = "~/dev/ProvisionScript/debian/debian-7.6-teamcity.sh"
    s.args = "sky 8.1.4 9.3"
  end
  
  
  config.vm.provider :google do |google, override|
    google.google_project_id = "just-site-684"
    google.google_client_email = "866246534971-g9lmcnhv5tegpmbf545q0hsb5col90lj@developer.gserviceaccount.com"
    google.google_key_location = "/home/sky/dev/credentials/googleCloud/Automation-f55555e2a2f3.p12"

    google.zone = "us-central1-f"

    google.zone_config "us-central1-f" do |zone1f|
        zone1f.name = "hs-ci"
        zone1f.image = "debian-7-wheezy-v20140924"
        zone1f.machine_type = "n1-standard-1"
        zone1f.zone = "us-central1-f"
    end

    override.ssh.username = "sky"
    override.ssh.private_key_path = "/home/sky/.ssh/id_rsa"
  end
end
